### ISSUE TITLE
result.sarif missing due to error in Run Slither step: KeyError: 'detectors'

### ISSUE THREAD

**Issue by fabianorodrigo** [crytic/slither-action#20]
Hi!

I've created a job to run slither pretty similar to the example in the marketplace page: https://github.com/marketplace/actions/slither-action

```
  slither:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        id: slither
        continue-on-error: true
        with:
          sarif: results.sarif
          # slither-config: .//slither.config.json
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
```

However, the step "Upload SAFIF file" fails missing the result.sarif file: Path does not exist: results.sarif.

Looking at the step "Run Slither" logs, I find this error (in spite of the step is not marked as failed):

```
'npx hardhat compile --force' running
Generating typings for: 23 artifacts in dir: typechain-types for target: ethers-v5
Successfully generated 72 typings!
Compiled 23 Solidity files successfully

. analyzed (23 contracts with 59 detectors), 0 result(s) found
Traceback (most recent call last):
  File "/opt/slither/bin/slither", line 8, in <module>
    sys.exit(main())
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 632, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 820, in main_impl
    output_to_sarif(
  File "/opt/slither/lib/python3.9/site-packages/slither/utils/output.py", line 163, in output_to_sarif
    for detector in results["detectors"]:
KeyError: 'detectors'
```

Thank you for any help

**Comment by elopez** [comment]
Hi, thanks for the report! This looks like the following slither bug, which causes an error when there are no results and sarif output is enabled: crytic/slither#1228. A fix for it has been merged in slither and this issue should be resolved when the next version is released.

**Comment by liron-navon** [comment]
@elopez any news on release date? I have something similar and I imagine they are connected:

https://github.com/crytic/slither-action/issues/25

**Comment by elopez** [comment]
I don't have any dates to share, but it should happen soon. You can track the progress here: https://github.com/crytic/slither/issues/1252

**Comment by xanderdunn** [comment]
In the mean time, is there any way to fix our CI? I see there is a `slither-version` option, but does it only take tagged version numbers, or can it pull a specific commit hash? Does rolling back to slither 0.8.2 fix it?

**Comment by elopez** [comment]
Unfortunately it currently only accepts released versions in PyPI; a way to run with `dev` / `master` sounds like an useful feature, please create a GitHub issue and we can work on that 😄

Meanwhile, you can disable the SARIF integration (remove the `sarif` option in the action) temporarily, and that should work around this failure. Or you can add a harmless issue that is picked up by Slither in the code, so you have at least 1 detection on all runs. This bug only happens when there's zero detections.

**Comment by elopez** [comment]
Slither 0.9.0 and slither-action 0.2.0 are out now 🎉  so this should no longer be a problem. I'll close this issue but feel free to open a new one if you still have a problem!
