### ISSUE TITLE
Work with `pnpm`?

### ISSUE THREAD

**Issue by 0xCLARITY** [crytic/slither-action#24]
Hi there,

I was trying to switch our contract repo from using Yarn to PNPM, but it looks like the Slither Action doesn't know how to autoinstall dependencies from a `pnpm-lock.yaml` rather than a `yarn.lock` file. Happy to write a PR if I know where to look.

**Comment by elopez** [comment]
Hi! I'll be happy to take a PR for this 👍  you can find the part that deals with installing npm deps here: https://github.com/crytic/slither-action/blob/main/entrypoint.sh#L115-L129

**Comment by hansbergren** [comment]
https://github.com/crytic/slither-action/pull/27

**Comment by elopez** [comment]
Thanks again for the contribution, this should be out in the next action release! 🎉
