### ISSUE TITLE
no way to provide remappings to crytic-compile

### ISSUE THREAD

**Issue by RatanRSur** [crytic/slither-action#3]
When I run slither locally I can pass it
```
--solc-remaps "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/ @openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
```
and it passes this down to the compiler.

I think this doesn't work with this action because crytic-compile is called separately and doesn't get these args and so fails before slither is called.

**Comment by elopez** [comment]
Hi @RatanRSur, thanks for the report. Indeed, crytic-compile is called separately - I don't recall if there was a specific reason for it being implemented that way, maybe @smichaels-tob remembers?

I feel it should be possible to skip it and call slither directly. Slither itself should invoke crytic-compile already. That way you would be able to remap via `slither-config`
