### ISSUE TITLE
slither-version should pull a hash or specific branch from GitHub

### ISSUE THREAD

**Issue by xanderdunn** [crytic/slither-action#31]
Rather than only published tagged versions, it would be convenient to be able to specify a particular commit hash, or a branch of the `slither` project to be used by slither-action. 

This feature would allow us to circumvent #20 right now. In the future it will inevitably be useful when bugs or features are introduced or fixed in slither.

**Comment by elopez** [comment]
Thanks for the feature request! If you have the time, you can give PR #32 a try (`using: crytic/slither-action@dev-github-versions`) and let us know how it goes

**Comment by xanderdunn** [comment]
Thanks, that was fast!
