### ISSUE TITLE
Fail-On ignores `slither.db.json`

### ISSUE THREAD

**Issue by 0xGuybrush** [crytic/slither-action#57]
## Steps to reproduce

1. Create a new project within `forge init`
2. Run `slither . --fail-low`. Notice that the command will fail (e.g `echo $?` returns non-zero).
3. Run `slither . --triage-mode` and accept "All" for each warning generated. `slither.db.json` is created
4. Re-run  `slither . --fail-low` — it now passes successfull (and `echo $?` returns 0).
5. Configure the GH action with `fail-on: low`.

### Current outcome

* Slither Action fails the build. In its error output, it shows issues that have been ignored by `slither.db.json`

### Desired outcome

* Sither Action honours the `slither.db.json` file and ignores hidden issues

**Comment by elopez** [comment]
Hi @0xGuybrush! Thanks for the report. Could you provide more info or a link to a repo with a workflow run exhibiting this problem? I tried to reproduce it with your instructions, but it is working fine as far as I can tell:

Sample repo: https://github.com/elopez/slither-action-triage-57 (just `forge init` plus a simple slither action workflow and the `--triage-mode` db committed).
Workflow run: https://github.com/elopez/slither-action-triage-57/actions/runs/4876725376/jobs/8700569156

![Screenshot 2023-05-03 at 18 34 11](https://user-images.githubusercontent.com/2642849/236054850-4f028fee-9ec4-4311-968b-770dbef90852.png)

Here's some things that you can check in case they're making a difference:
* that foundry is up to date and using the same solc version locally and on the CI
* that the slither versions match in CI and locally (some detectors may have been e.g. renamed)
* that, if you're using a `target` different than `.`, you committed the slither db file in your repository root (AFAICT slither picks it up from cwd, not from the target folder)

**Comment by 0xGuybrush** [comment]
Hi @elopez,

thanks for the quick reply and sorrying I'm only getting back to you now! Cool, I will indeed. I thought my repo was vanilla enough, but I'll go back & double-check where mine diverged. I reckon it might be the solc version between local & CI.

I'll take a look and if I can reproduce on a clean repro I'll let you know.

Thanks for your help!

**Comment by 0xGuybrush** [comment]
@elopez this was a red herring, I realised from your pointer that I'd created the DB on one `solc` version but was running with a different one & when I recreated the issue went away.

Thanks again, will close this out now.
