### ISSUE TITLE
Slither args not working

### ISSUE THREAD

**Issue by dino-rodriguez** [crytic/slither-action#6]
Slither args don't work. Looking at  `action-yaml` they don't even get passed into the Dockerfile?

**Comment by elopez** [comment]
Hi @dino-rodriguez, thanks for the report! The slither args get fetched from the environment here

https://github.com/crytic/slither-action/blob/main/entrypoint.sh#L14

And are passed to slither here:

https://github.com/crytic/slither-action/blob/main/entrypoint.sh#L148-L151

If you are having an issue with them, would you mind sharing how are you calling the action, what you expect to happen and what actually happens?

In case it's useful, you can also use a slither config file, which should let you configure slither without having to use arguments as well.
