### ISSUE TITLE
Error: Cant find module '@nomicfoundation/hardhat-chai-matchers'

### ISSUE THREAD

**Issue by nelly45er** [crytic/slither-action#60]
might be easy fix but:
this is the error i cant get past once i try to run -npx hardhat-
any recommendations on how to get hardhat running following this?
![Screen Shot 2023-05-13 at 10 53 17 AM](https://github.com/crytic/slither-action/assets/133520077/eb98c5de-733e-4b33-a04f-fa42d3307c2c)

**Comment by elopez** [comment]
Hi! This is not the Hardhat repo, you might want to ask there. From here and without further context it looks like you might be missing some dependencies, try installing those with `npm i`.

**Comment by nelly45er** [comment]
after i have installed suggested dependencies, this is the error i get after running npx hardhat again. 
thanks for the direction. i will try to repost this question there
