### ISSUE TITLE
Error HH801-  when running NPX HARDHAT

### ISSUE THREAD

**Issue by nelly45er** [crytic/slither-action#61]
how do i get hardhat to run?
![Screen Shot 2023-05-13 at 11 52 28 AM](https://github.com/crytic/slither-action/assets/133520077/33d8be87-364b-4b57-9e0a-78dd8444bab8)

**Comment by elopez** [comment]
Hi! This is not the Hardhat repo, you might want to ask there. From here and without further context it looks like you might be missing some dependencies, try installing those with `npm i`.
