### ISSUE TITLE
npm ERR! code EUNSUPPORTEDPROTOCOL

### ISSUE THREAD

**Issue by AaronLee22** [crytic/slither-action#72]
[-] Foundry target detected, installing foundry nightly

.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx
 
 ╔═╗ ╔═╗ ╦ ╦ ╔╗╔ ╔╦╗ ╦═╗ ╦ ╦         Portable and modular toolkit
 ╠╣  ║ ║ ║ ║ ║║║  ║║ ╠╦╝ ╚╦╝    for Ethereum Application Development 
 ╚   ╚═╝ ╚═╝ ╝╚╝ ═╩╝ ╩╚═  ╩                 written in Rust.

.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx

Repo       : https://github.com/foundry-rs/
Book       : https://book.getfoundry.sh/                      
Chat       : https://t.me/foundry_rs/                         
Support    : https://t.me/foundry_support/
Contribute : https://github.com/orgs/foundry-rs/projects/2/

.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx

foundryup: installing foundry (version nightly, tag nightly)
foundryup: downloading latest forge, cast, anvil, and chisel
#=#=#                                                                         

######################################################################## 100.0%
foundryup: downloading manpages
#=#=#                                                                         

######################################################################## 100.0%
foundryup: installed - forge 0.2.0 (de33b6a 2024-03-02T00:15:47.606546623Z)
foundryup: installed - cast 0.2.0 (de33b6a 2024-03-02T00:15:47.607795141Z)
foundryup: installed - anvil 0.2.0 (de33b6a 2024-03-02T00:15:47.606162572Z)
foundryup: installed - chisel 0.2.0 (de33b6a 2024-03-02T00:15:47.607088016Z)
foundryup: done!
[-] Did not detect a package-lock.json, yarn.lock, or pnpm-lock.yaml in packages/tokamak/contracts-bedrock, consider locking your dependencies!
[-] Proceeding with 'npm i' to install dependencies
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in: /github/home/.npm/_logs/2024-03-02T12_10_27_579Z-debug-0.log

after proceeding with 'npm i' to install dependencies, there is an error says 'npm ERR! code EUNSUPPORTEDPROTOCOL'. 
Can you help me solve this problem?

**Comment by elopez** [comment]
Hi @AaronLee22! There seems to be an issue installing the dependencies for your project. The action is running `npm i` in the `packages/tokamak/contracts-bedrock` directory but for some reason that fails on your codebase. See if that happens locally as well, and if needed, adjust the node version the action uses with the `node-version` parameter.

If you're using another tool to manage your dependencies (e.g. yarn, pnpm) consider committing your lock file (package-lock.json, yarn.lock, or pnpm-lock.yaml, as highlighted in the log). That will hint the action as to what tool to use for the job.

**Comment by AaronLee22** [comment]
"Thanks for your response. I'm utilizing pnpm to handle dependencies. I'm aware that the 'Run Slither' step operates within a distinct Docker container. Could you guide me on how to execute a pnpm install?"

**Comment by AaronLee22** [comment]
it works fine now! Thank you for your help!
