### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by mds1** [crytic/slither-action#74]
This repo is missing a license file, I'm guessing it should be the AGPL-3.0 license that other ToB tools seem to use?

**Comment by elopez** [comment]
Hi @mds1! Good catch! I believe this should be AGPL-3.0 like we have for [echidna-action](https://github.com/crytic/echidna-action/blob/master/LICENSE) and [slither-docs-action](https://github.com/crytic/slither-docs-action/blob/main/LICENSE.md), but I'll check internally and make a PR to add the proper license file.

**Comment by mds1** [comment]
Great, thank you!

**Comment by elopez** [comment]
Closing as this is now merged and released :shipit: Thanks again for reporting!
